// Generated by CoffeeScript 1.9.3
$(function() {
  var clone, dont_animate, expand, height, revert, tabs;
  $("a[data-toggle='tooltip']").tooltip();
  $("#load").css({
    display: 'none'
  });
  $("#not-done").css({
    display: 'none'
  });
  $(".about-me").css({
    display: 'none'
  });
  $(window).unload(function() {
    return $('body').scrollTop(0);
  });
  height = window.innerHeight + 4;
  $("#invisible-line").css({
    top: height
  });
  console.log($("#player")[0]);
  
	function isElementInViewport (el) {

	    //special bonus for those using jQuery
	    if (typeof jQuery === "function" && el instanceof jQuery) {
	        el = el[0];
	    }

	    var rect = el.getBoundingClientRect();

	    return (
	        rect.top >= 0 &&
	        rect.left >= 0 &&
	        rect.bottom <= (window.innerHeight || document.documentElement.clientHeight) && /*or $(window).height() */
	        rect.right <= (window.innerWidth || document.documentElement.clientWidth) /*or $(window).width() */
	    );
	}
	;
  dont_animate = false;
  $("a[data-toggle='tooltip']").bind('click', function() {
    return dont_animate = true;
  });
  $(".post:not(a[data-toggle='tooltip'])").bind('click', function(e) {
    var $extra, height_animate, id;
    if (dont_animate) {
      dont_animate = false;
      return;
    }
    id = $(this).attr('id');
    $extra = $("#extra" + id);
    if ($extra.attr('status') === "closed") {
      height_animate = $extra.attr('ht');
      if (height_animate == null) {
        height_animate = $extra.children().first().height();
      } else {
        height_animate = parseInt(height_animate);
      }
      $extra.attr('status', 'open');
      return $extra.velocity({
        height: (height_animate + 10) + "px"
      }, {
        duration: 500
      });
    } else {
      $extra.attr('status', 'closed');
      return $extra.velocity({
        height: "160px"
      }, {
        duration: 500
      });
    }
  });
  revert = function() {
    if (isElementInViewport($("#invisible-line-2"))) {
      $("#cover-page").velocity("reverse");
      $("#feed-content").velocity({
        translateY: '0px',
        duration: 500
      });
      $('.header').velocity({
        translateY: '0px'
      }, {
        duration: 500
      });
      $(".subheader").velocity({
        opacity: 0.85,
        translateY: '0px'
      }, {
        duration: 500
      });
      $('#profile').velocity({
        opacity: 1,
        translateY: '0px'
      }, {
        duration: 500
      });
      $(window).unbind('scroll');
      return $(window).scroll(expand);
    }
  };
  expand = function() {
    if (isElementInViewport($('#invisible-line'))) {
      console.log("In View");
      $("#cover-page").velocity({
        height: '80px'
      }, {
        duration: 500
      });
      $("#feed-content").velocity({
        translateY: '-230px'
      }, {
        duration: 500
      });
      $(".subheader").velocity({
        opacity: 0,
        translateY: '-150px'
      }, {
        duration: 500
      });
      $('#profile').velocity({
        opacity: 0,
        translateY: '-150px'
      }, {
        duration: 500
      });
      $('.header').velocity({
        translateY: '-150px'
      }, {
        duration: 500
      });
      $(window).unbind('scroll');
      return $(window).scroll(revert);
    }
  };
  $(window).scroll(expand);
  tabs = {
    'About Me': 'A',
    'Skills': 'S',
    'Projects': 'P',
    'Experience': 'E',
    'Contact Me': 'last-li'
  };
  clone = $("#player").first().clone(true);
  return $("#nav-id").bind('click', function(e) {
    var $clicked, $new_tab, new_tab;
    clone = $("#player").first().clone(true);
    $clicked = $(e.target);
    if ($clicked.prop("tagName") === "LI") {
      new_tab = $clicked.text();
      new_tab = tabs["" + new_tab];
      $new_tab = $("#" + new_tab);
      $(".active").first().removeClass('active');
      $new_tab.addClass("active");
      if (new_tab === 'S' || new_tab === 'E' || new_tab === 'last-li') {
        $('.about-me').css({
          display: 'none'
        });
        $("#not-done").css({
          display: 'none'
        });
        $(".projects").css({
          display: 'none'
        });
        $("#load").css({
          display: 'block'
        });
        return setTimeout(function() {
          $("#not-done").css({
            display: 'block'
          });
          return $("#load").css({
            display: 'none'
          });
        }, 300);
      } else if (new_tab === 'P') {
        $('.about-me').css({
          display: 'none'
        });
        $("#not-done").css({
          display: 'none'
        });
        $(".projects").css({
          display: 'none'
        });
        $("#load").css({
          display: 'block'
        });
        return setTimeout(function() {
          $(".projects").css({
            display: 'block'
          });
          $("#load").css({
            display: 'none'
          });
          $("#player").first().remove();
          return $("#extra1").prepend(clone);
        }, 300);
      } else {
        $('.about-me').css({
          display: 'none'
        });
        $("#not-done").css({
          display: 'none'
        });
        $(".projects").css({
          display: 'none'
        });
        $("#load").css({
          display: 'block'
        });
        return setTimeout(function() {
          $(".about-me").css({
            display: 'block'
          });
          return $("#load").css({
            display: 'none'
          });
        }, 300);
      }
    }
  });
});
