// Generated by CoffeeScript 1.9.3
$(function() {
  var expand, height, revert;
  $(window).unload(function() {
    return $('body').scrollTop(0);
  });
  height = window.innerHeight + 4;
  $("#invisible-line").css({
    top: height
  });
  
	function isElementInViewport (el) {

	    //special bonus for those using jQuery
	    if (typeof jQuery === "function" && el instanceof jQuery) {
	        el = el[0];
	    }

	    var rect = el.getBoundingClientRect();

	    return (
	        rect.top >= 0 &&
	        rect.left >= 0 &&
	        rect.bottom <= (window.innerHeight || document.documentElement.clientHeight) && /*or $(window).height() */
	        rect.right <= (window.innerWidth || document.documentElement.clientWidth) /*or $(window).width() */
	    );
	}
	;
  revert = function() {
    if (isElementInViewport($("#invisible-line-2"))) {
      $("#cover-page").velocity("reverse");
      $("#feed-content").velocity({
        translateY: '0px',
        duration: 500
      });
      $('.header').velocity({
        translateY: '0px'
      }, {
        duration: 500,
        complete: function() {
          $(".subheader").velocity({
            opacity: 0.85
          }, {
            duration: 300
          });
          return $('#profile').velocity({
            opacity: 1
          }, {
            duration: 300
          });
        }
      });
      $(window).unbind('scroll');
      return $(window).scroll(expand);
    }
  };
  expand = function() {
    if (isElementInViewport($('#invisible-line'))) {
      console.log("In View");
      $("#cover-page").velocity({
        height: '80px'
      }, {
        duration: 500
      });
      $("#feed-content").velocity({
        translateY: '-230px'
      }, {
        duration: 500
      });
      $(".subheader").velocity({
        opacity: 0
      }, {
        duration: 300
      });
      $('#profile').velocity({
        opacity: 0
      }, {
        duration: 300
      });
      $('.header').velocity({
        translateY: '-153px'
      }, {
        duration: 500
      });
      $(window).unbind('scroll');
      return $(window).scroll(revert);
    }
  };
  return $(window).scroll(expand);
});
